### ISSUE TITLE
Constructor not found

### ISSUE THREAD

**Issue by dome4** [harrison-ifeanyichukwu/xml-serializer#1]
I receive a `UnhandledPromiseRejectionWarning: TypeError: xml_serializer_1.default is not a constructor` when using your default examlpe: 

```
import XMLSerializer from '@harrison-ifeanyichukwu/xml-serializer';
let instance = new XMLSerializer();
```

P.S. Great Job, have been searching for a couple of days for a fitting lib like this

**Comment by dome4** [comment]
importing the module as XMLSerializer solves the issue for myself:
`import * as XMLSerializer from '@harrison-ifeanyichukwu/xml-serializer';`

**Comment by harrison-ifeanyichukwu** [comment]
Thats great to hear @dome4. and thanks for reporting. I just tested this from my own end. and it is working fine.

Both using `es6` import and node.js `require`

```
> let mod = require('@harrison-ifeanyichukwu/xml-serializer')
undefined
> console.log(mod)
[Function: XMLSerializer]
undefined
>
```

Please can you shed more light into your code! I would really appreciate

**Comment by harrison-ifeanyichukwu** [comment]
Hello @dome4 , please can i get a feedback from you before i proceed to close this issue

**Comment by dome4** [comment]
I retried the import in an empty node.js-project and it worked fine, too. So I'm not sure, why the import didn't work in my previous project: https://github.com/dome4/office-addin-backend/blob/master/VersionControlBackend/controllers/office.controller.ts

Nevertheless, thanks for your feedback 👍

**Comment by harrison-ifeanyichukwu** [comment]
Thanks for the feedback. I guess all working at the moment then
